include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_declarations: false
    prefer_const_constructors: false
    unnecessary_this: false
    override_on_non_overriding_member: false
